TARGET		:= Xtest08_3

C_OBJECTS	:= $(TARGET).o
C_OBJECTS	+= buzzer.o delay.o key.o sll.o tick.o
C_OBJECTS	+= aic.o
C_OBJECTS	+= lcd.o
C_OBJECTS	+= led.o
C_OBJECTS	+= pio.o
C_OBJECTS	+= pio_it.o
C_OBJECTS	+= pit.o

include ../at91sam7s.mk
